# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(495, 435)
        self.centralwidget = QtWidgets.QWidget(LoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_Main = QtWidgets.QLabel(self.centralwidget)
        self.label_Main.setGeometry(QtCore.QRect(10, 10, 471, 411))
        self.label_Main.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(255, 255, 255);")
        self.label_Main.setText("")
        self.label_Main.setObjectName("label_Main")
        self.BT_exit = QtWidgets.QPushButton(self.centralwidget)
        self.BT_exit.setGeometry(QtCore.QRect(400, 20, 51, 41))
        self.BT_exit.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"font: 16pt \"楷体\";\n"
"color: rgb(0, 170, 255);\n"
"}\n"
"\n"
"")
        self.BT_exit.setObjectName("BT_exit")
        self.BT_Login = QtWidgets.QPushButton(self.centralwidget)
        self.BT_Login.setGeometry(QtCore.QRect(170, 290, 161, 41))
        self.BT_Login.setStyleSheet("QPushButton{\n"
"font: 16pt \"楷体\";\n"
"background:rgb(0,170,255);\n"
"border-radius:20px;\n"
"border: 2px groove gray;\n"
"border-style: outset;\n"
"}\n"
"\n"
"QPushButton:hover{background:rgb(0,220,255);}\n"
"\n"
"")
        self.BT_Login.setObjectName("BT_Login")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 140, 91, 31))
        self.label.setStyleSheet("border-radius:20px;\n"
"font: 16pt \"楷体\";\n"
"color: rgb(0，0，0);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(190, 70, 121, 31))
        self.label_2.setStyleSheet("font: 16pt \"楷体\";")
        self.label_2.setObjectName("label_2")
        self.lineEdit_account = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_account.setGeometry(QtCore.QRect(170, 140, 201, 31))
        self.lineEdit_account.setStyleSheet("border-radius:15px;\n"
"border: 2px groove gray;\n"
"border-style: inset;")
        self.lineEdit_account.setObjectName("lineEdit_account")
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(80, 210, 91, 31))
        self.label_1.setStyleSheet("border-radius:20px;\n"
"font: 16pt \"楷体\";\n"
"color: rgb(0，0，0);")
        self.label_1.setObjectName("label_1")
        self.lineEdit_passwd = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_passwd.setGeometry(QtCore.QRect(170, 210, 201, 31))
        self.lineEdit_passwd.setStyleSheet("border-radius:15px;\n"
"border: 2px groove gray;\n"
"border-style: inset;")
        self.lineEdit_passwd.setInputMask("")
        self.lineEdit_passwd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_passwd.setObjectName("lineEdit_passwd")
        self.BT_viewPasswd = QtWidgets.QPushButton(self.centralwidget)
        self.BT_viewPasswd.setGeometry(QtCore.QRect(340, 216, 21, 20))
        self.BT_viewPasswd.setStyleSheet("border-radius:20px;")
        self.BT_viewPasswd.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resource/enview.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BT_viewPasswd.setIcon(icon)
        self.BT_viewPasswd.setObjectName("BT_viewPasswd")
        self.BT_hidePasswd = QtWidgets.QPushButton(self.centralwidget)
        self.BT_hidePasswd.setGeometry(QtCore.QRect(340, 216, 21, 20))
        self.BT_hidePasswd.setStyleSheet("border-radius:20px;")
        self.BT_hidePasswd.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("resource/disview.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BT_hidePasswd.setIcon(icon1)
        self.BT_hidePasswd.setObjectName("BT_hidePasswd")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 20, 161, 31))
        self.label_3.setStyleSheet("background-color: rgb(0, 180, 255);\n"
"border-radius:15px;")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("resource/logo2.png"))
        self.label_3.setScaledContents(False)
        self.label_3.setObjectName("label_3")
        LoginWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "LoginWindow"))
        self.BT_exit.setText(_translate("LoginWindow", "退出"))
        self.BT_Login.setText(_translate("LoginWindow", "登录"))
        self.label.setText(_translate("LoginWindow", "用户名："))
        self.label_2.setText(_translate("LoginWindow", "管理员登录"))
        self.lineEdit_account.setPlaceholderText(_translate("LoginWindow", "请输入账号"))
        self.label_1.setText(_translate("LoginWindow", "密  码："))
        self.lineEdit_passwd.setPlaceholderText(_translate("LoginWindow", "请输入密码"))
