# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window_inform.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_window_inform(object):
    def setupUi(self, window_inform):
        window_inform.setObjectName("window_inform")
        window_inform.resize(1294, 757)
        self.centralwidget = QtWidgets.QWidget(window_inform)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.label_background = QtWidgets.QLabel(self.centralwidget)
        self.label_background.setEnabled(True)
        self.label_background.setGeometry(QtCore.QRect(0, 0, 1280, 720))
        self.label_background.setStyleSheet("QLabel {\n"
"background-image: url(\'resource/background2.jpg\');\n"
"border-radius: 15px;\n"
"}")
        self.label_background.setText("")
        self.label_background.setScaledContents(False)
        self.label_background.setObjectName("label_background")
        self.label_logo = QtWidgets.QLabel(self.centralwidget)
        self.label_logo.setGeometry(QtCore.QRect(0, 10, 191, 41))
        self.label_logo.setStyleSheet("\n"
"border-radius:15px;")
        self.label_logo.setText("")
        self.label_logo.setPixmap(QtGui.QPixmap("resource/logo2.png"))
        self.label_logo.setScaledContents(True)
        self.label_logo.setObjectName("label_logo")
        self.BT_exit = QtWidgets.QPushButton(self.centralwidget)
        self.BT_exit.setGeometry(QtCore.QRect(1200, 10, 51, 41))
        self.BT_exit.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"font: 16pt \"楷体\" blod;\n"
"color: rgb(0, 90, 255);\n"
"}\n"
"\n"
"")
        self.BT_exit.setObjectName("BT_exit")
        self.groupBox_1 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_1.setGeometry(QtCore.QRect(10, 100, 881, 531))
        self.groupBox_1.setStyleSheet("QGroupBox{\n"
"border-radius:20px;\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.groupBox_1.setTitle("")
        self.groupBox_1.setObjectName("groupBox_1")
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox_1)
        self.tableWidget.setGeometry(QtCore.QRect(20, 20, 831, 492))
        self.tableWidget.setStyleSheet("border-radius:20px;\n"
"font: 75 14pt \"微软雅黑\";")
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setShowGrid(False)
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(300)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(50)
        self.textBrowser = QtWidgets.QTextBrowser(self.groupBox_1)
        self.textBrowser.setGeometry(QtCore.QRect(10, 10, 861, 511))
        self.textBrowser.setStyleSheet("QTextBrowser{\n"
"border-radius:20px;\n"
"background-color: rgb(255, 255, 255);\n"
"font: 75 18pt \"微软雅黑\";\n"
"}")
        self.textBrowser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser.setObjectName("textBrowser")
        self.BT_close = QtWidgets.QPushButton(self.groupBox_1)
        self.BT_close.setGeometry(QtCore.QRect(830, 10, 41, 41))
        self.BT_close.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"border-image: url(\'resource/close.png\');\n"
"background-color: rgba(0, 0, 0,0);\n"
"color: rgba(0, 90, 255,0.5);\n"
"}\n"
"QPushButton:hover{background:rgba(0,255,255,0.1);}\n"
"\n"
"")
        self.BT_close.setText("")
        self.BT_close.setIconSize(QtCore.QSize(51, 41))
        self.BT_close.setObjectName("BT_close")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(910, 100, 351, 531))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_background2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_background2.setGeometry(QtCore.QRect(0, 0, 351, 531))
        self.label_background2.setStyleSheet("QLabel {\n"
"background-image: url(\'resource/background.png\');\n"
"border-radius: 15px;\n"
"}")
        self.label_background2.setText("")
        self.label_background2.setScaledContents(False)
        self.label_background2.setObjectName("label_background2")
        self.label_info = QtWidgets.QLabel(self.centralwidget)
        self.label_info.setGeometry(QtCore.QRect(410, 40, 481, 51))
        self.label_info.setStyleSheet("\n"
"font: 75 24pt \"微软雅黑\";")
        self.label_info.setObjectName("label_info")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.dateTimeEdit.setGeometry(QtCore.QRect(960, 16, 231, 31))
        self.dateTimeEdit.setStyleSheet("border-radius:20px;\n"
"font: 16pt \"幼圆\" blod;\n"
"background-color: rgb(227, 229, 244);\n"
"")
        self.dateTimeEdit.setWrapping(False)
        self.dateTimeEdit.setFrame(False)
        self.dateTimeEdit.setReadOnly(True)
        self.dateTimeEdit.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.dateTimeEdit.setKeyboardTracking(False)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.BT_1 = QtWidgets.QPushButton(self.centralwidget)
        self.BT_1.setGeometry(QtCore.QRect(160, 640, 191, 61))
        self.BT_1.setStyleSheet("QPushButton {\n"
"image: url(\'resource/classinfor.png\');\n"
"background-color: rgba(255, 255, 255, 0.8);\n"
"border-radius: 20px;\n"
"font: 75 16pt \"微软雅黑\";\n"
"}\n"
"\n"
"QPushButton:hover{background:rgba(255,255,255,1.0);}")
        self.BT_1.setObjectName("BT_1")
        self.BT_2 = QtWidgets.QPushButton(self.centralwidget)
        self.BT_2.setGeometry(QtCore.QRect(390, 640, 191, 61))
        self.BT_2.setStyleSheet("QPushButton {\n"
"image: url(\'resource/check.png\');\n"
"background-color: rgba(255, 255, 255, 0.8);\n"
"border-radius: 20px;\n"
"font: 75 16pt \"微软雅黑\";\n"
"}\n"
"\n"
"QPushButton:hover{background:rgba(255,255,255,1.0);}")
        self.BT_2.setObjectName("BT_2")
        self.BT_3 = QtWidgets.QPushButton(self.centralwidget)
        self.BT_3.setGeometry(QtCore.QRect(610, 640, 191, 61))
        self.BT_3.setStyleSheet("QPushButton {\n"
"image: url(\'resource/notice.png\');\n"
"background-color: rgba(255, 255, 255, 0.8);\n"
"border-radius: 20px;\n"
"font: 75 16pt \"微软雅黑\";\n"
"}\n"
"\n"
"QPushButton:hover{background:rgba(255,255,255,1.0);}")
        self.BT_3.setObjectName("BT_3")
        self.BT_4 = QtWidgets.QPushButton(self.centralwidget)
        self.BT_4.setGeometry(QtCore.QRect(830, 640, 191, 61))
        self.BT_4.setStyleSheet("QPushButton {\n"
"image: url(\'resource/opendoor.png\');\n"
"background-color: rgba(255, 255, 255, 0.8);\n"
"border-radius: 20px;\n"
"font: 75 16pt \"微软雅黑\";\n"
"}\n"
"\n"
"QPushButton:hover{background:rgba(255,255,255,1.0);}")
        self.BT_4.setObjectName("BT_4")
        self.label_background.raise_()
        self.label_logo.raise_()
        self.BT_exit.raise_()
        self.groupBox_1.raise_()
        self.label_info.raise_()
        self.dateTimeEdit.raise_()
        self.groupBox_2.raise_()
        self.BT_1.raise_()
        self.BT_2.raise_()
        self.BT_3.raise_()
        self.BT_4.raise_()
        window_inform.setCentralWidget(self.centralwidget)

        self.retranslateUi(window_inform)
        QtCore.QMetaObject.connectSlotsByName(window_inform)

    def retranslateUi(self, window_inform):
        _translate = QtCore.QCoreApplication.translate
        window_inform.setWindowTitle(_translate("window_inform", "window_inform"))
        self.BT_exit.setText(_translate("window_inform", "退出"))
        self.textBrowser.setHtml(_translate("window_inform", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'微软雅黑\'; font-size:18pt; font-weight:72; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_info.setText(_translate("window_inform", "教学区-图文信息中心TB504"))
        self.dateTimeEdit.setDisplayFormat(_translate("window_inform", "yyyy-MM-dd HH:mm:ss"))
        self.BT_1.setToolTip(_translate("window_inform", "<html><head/><body><p><br/></p></body></html>"))
        self.BT_1.setText(_translate("window_inform", "          课程信息"))
        self.BT_2.setText(_translate("window_inform", "      人像考勤"))
        self.BT_3.setText(_translate("window_inform", "      通知公告"))
        self.BT_4.setText(_translate("window_inform", "       一键开门"))
