# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window_opendoor.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_window_opendoor(object):
    def setupUi(self, window_opendoor):
        window_opendoor.setObjectName("window_opendoor")
        window_opendoor.resize(1287, 744)
        self.centralwidget = QtWidgets.QWidget(window_opendoor)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.label_background = QtWidgets.QLabel(self.centralwidget)
        self.label_background.setEnabled(True)
        self.label_background.setGeometry(QtCore.QRect(0, 0, 1280, 720))
        self.label_background.setStyleSheet("QLabel {\n"
"background-image: url(\'resource/背景图.png\');\n"
"border-radius: 15px;\n"
"}")
        self.label_background.setText("")
        self.label_background.setScaledContents(False)
        self.label_background.setObjectName("label_background")
        self.label_logo = QtWidgets.QLabel(self.centralwidget)
        self.label_logo.setGeometry(QtCore.QRect(0, 10, 191, 41))
        self.label_logo.setStyleSheet("\n"
"border-radius:15px;")
        self.label_logo.setText("")
        self.label_logo.setPixmap(QtGui.QPixmap("resource/logo2.png"))
        self.label_logo.setScaledContents(True)
        self.label_logo.setObjectName("label_logo")
        self.BT_exit = QtWidgets.QPushButton(self.centralwidget)
        self.BT_exit.setGeometry(QtCore.QRect(1200, 10, 51, 41))
        self.BT_exit.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"font: 16pt \"楷体\" blod;\n"
"color: rgb(0, 90, 255);\n"
"}\n"
"\n"
"")
        self.BT_exit.setObjectName("BT_exit")
        self.label_camera = QtWidgets.QLabel(self.centralwidget)
        self.label_camera.setGeometry(QtCore.QRect(285, 10, 711, 701))
        self.label_camera.setStyleSheet("QLabel{border-radius:350px;\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.label_camera.setText("")
        self.label_camera.setScaledContents(False)
        self.label_camera.setObjectName("label_camera")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.dateTimeEdit.setGeometry(QtCore.QRect(960, 16, 231, 31))
        self.dateTimeEdit.setStyleSheet("border-radius:20px;\n"
"font: 16pt \"幼圆\" blod;\n"
"background-color: rgb(227, 229, 244);\n"
"")
        self.dateTimeEdit.setWrapping(False)
        self.dateTimeEdit.setFrame(False)
        self.dateTimeEdit.setReadOnly(True)
        self.dateTimeEdit.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.dateTimeEdit.setKeyboardTracking(False)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(360, 0, 541, 91))
        self.label.setStyleSheet("font: 18pt \"微软雅黑\";\n"
"\n"
"color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.BT_opendoor = QtWidgets.QPushButton(self.centralwidget)
        self.BT_opendoor.setGeometry(QtCore.QRect(470, 620, 331, 71))
        self.BT_opendoor.setStyleSheet("QPushButton{\n"
"font: 18pt \"微软雅黑\";\n"
"border-radius: 20px;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 170, 255);\n"
"}\n"
"\n"
"QPushButton:hover{background:rgb(0, 150, 255);}")
        self.BT_opendoor.setObjectName("BT_opendoor")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 1281, 721))
        self.groupBox.setStyleSheet("QGroupBox{\n"
"background-color: rgba(220, 220, 220,0.5);\n"
"\n"
"border-radius:20px;\n"
"}")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(260, 190, 741, 371))
        self.groupBox_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(20, 40, 221, 51))
        self.label_2.setStyleSheet("font: 18pt \"微软雅黑\";\n"
"\n"
"color: rgb(0, 0, 0);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit.setGeometry(QtCore.QRect(30, 120, 631, 71))
        self.lineEdit.setStyleSheet("font: 14pt \"微软雅黑\";\n"
"background-color: rgba(235, 235, 235,0.5);\n"
"border-radius:20px;\n"
"color: rgb(0, 0, 0);")
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit.setObjectName("lineEdit")
        self.BT_confirm = QtWidgets.QPushButton(self.groupBox_2)
        self.BT_confirm.setGeometry(QtCore.QRect(30, 240, 271, 51))
        self.BT_confirm.setStyleSheet("QPushButton{\n"
"font: 16pt \"微软雅黑\";\n"
"border-radius: 15px;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgba(0, 170, 255,0.8);\n"
"}\n"
"\n"
"QPushButton:hover{background:rgb(0, 170, 255);}")
        self.BT_confirm.setObjectName("BT_confirm")
        self.BT_cancel = QtWidgets.QPushButton(self.groupBox_2)
        self.BT_cancel.setGeometry(QtCore.QRect(380, 240, 271, 51))
        self.BT_cancel.setStyleSheet("QPushButton{\n"
"font: 16pt \"微软雅黑\";\n"
"border-radius: 15px;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgba(220, 220, 220,0.7);\n"
"}\n"
"\n"
"QPushButton:hover{background:rgba(220, 220, 220,1);}")
        self.BT_cancel.setObjectName("BT_cancel")
        self.BT_viewPasswd = QtWidgets.QPushButton(self.groupBox_2)
        self.BT_viewPasswd.setGeometry(QtCore.QRect(600, 130, 51, 51))
        self.BT_viewPasswd.setStyleSheet("border-radius:25px;\n"
"background-color: rgba(235, 235, 235,0);\n"
"\n"
"")
        self.BT_viewPasswd.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resource/enview.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BT_viewPasswd.setIcon(icon)
        self.BT_viewPasswd.setIconSize(QtCore.QSize(40, 40))
        self.BT_viewPasswd.setObjectName("BT_viewPasswd")
        self.BT_hidePasswd = QtWidgets.QPushButton(self.groupBox_2)
        self.BT_hidePasswd.setGeometry(QtCore.QRect(600, 130, 51, 51))
        self.BT_hidePasswd.setStyleSheet("border-radius:25px;\n"
"background-color: rgba(235, 235, 235,0);\n"
"\n"
"")
        self.BT_hidePasswd.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("resource/disview.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BT_hidePasswd.setIcon(icon1)
        self.BT_hidePasswd.setIconSize(QtCore.QSize(40, 40))
        self.BT_hidePasswd.setObjectName("BT_hidePasswd")
        self.label_camera.raise_()
        self.label_background.raise_()
        self.label_logo.raise_()
        self.BT_exit.raise_()
        self.dateTimeEdit.raise_()
        self.label.raise_()
        self.BT_opendoor.raise_()
        self.groupBox.raise_()
        window_opendoor.setCentralWidget(self.centralwidget)

        self.retranslateUi(window_opendoor)
        QtCore.QMetaObject.connectSlotsByName(window_opendoor)

    def retranslateUi(self, window_opendoor):
        _translate = QtCore.QCoreApplication.translate
        window_opendoor.setWindowTitle(_translate("window_opendoor", "window_opendoor"))
        self.BT_exit.setText(_translate("window_opendoor", "退出"))
        self.dateTimeEdit.setDisplayFormat(_translate("window_opendoor", "yyyy-MM-dd HH:mm:ss"))
        self.label.setText(_translate("window_opendoor", "请 将 头 部 置 于 识 别 区 域 内"))
        self.BT_opendoor.setText(_translate("window_opendoor", "管理员密码开门"))
        self.label_2.setText(_translate("window_opendoor", "管理员密码开门"))
        self.lineEdit.setPlaceholderText(_translate("window_opendoor", "请输入"))
        self.BT_confirm.setText(_translate("window_opendoor", "确定"))
        self.BT_cancel.setText(_translate("window_opendoor", "取消"))
