# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window_check.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_window_check(object):
    def setupUi(self, window_check):
        window_check.setObjectName("window_check")
        window_check.resize(1293, 757)
        self.centralwidget = QtWidgets.QWidget(window_check)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.label_background = QtWidgets.QLabel(self.centralwidget)
        self.label_background.setEnabled(True)
        self.label_background.setGeometry(QtCore.QRect(0, 0, 1280, 720))
        self.label_background.setStyleSheet("QLabel {\n"
"background-image: url(\'resource/background2.jpg\');\n"
"border-radius: 15px;\n"
"}")
        self.label_background.setText("")
        self.label_background.setScaledContents(False)
        self.label_background.setObjectName("label_background")
        self.label_logo = QtWidgets.QLabel(self.centralwidget)
        self.label_logo.setGeometry(QtCore.QRect(0, 10, 191, 41))
        self.label_logo.setStyleSheet("\n"
"border-radius:15px;")
        self.label_logo.setText("")
        self.label_logo.setPixmap(QtGui.QPixmap("resource/logo2.png"))
        self.label_logo.setScaledContents(True)
        self.label_logo.setObjectName("label_logo")
        self.BT_exit = QtWidgets.QPushButton(self.centralwidget)
        self.BT_exit.setGeometry(QtCore.QRect(1200, 10, 51, 41))
        self.BT_exit.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"font: 16pt \"楷体\" blod;\n"
"color: rgb(0, 90, 255);\n"
"}\n"
"\n"
"")
        self.BT_exit.setObjectName("BT_exit")
        self.groupBox_1 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_1.setGeometry(QtCore.QRect(10, 100, 881, 531))
        self.groupBox_1.setStyleSheet("QGroupBox{border-radius:20px;\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.groupBox_1.setTitle("")
        self.groupBox_1.setObjectName("groupBox_1")
        self.label_camera = QtWidgets.QLabel(self.groupBox_1)
        self.label_camera.setGeometry(QtCore.QRect(10, 40, 858, 488))
        self.label_camera.setStyleSheet("QLabel{\n"
"border-radius:20px;\n"
"}")
        self.label_camera.setText("")
        self.label_camera.setScaledContents(False)
        self.label_camera.setObjectName("label_camera")
        self.label_course = QtWidgets.QLabel(self.groupBox_1)
        self.label_course.setGeometry(QtCore.QRect(270, 0, 321, 41))
        self.label_course.setStyleSheet("font: 75 16pt \"微软雅黑\";\n"
"")
        self.label_course.setText("")
        self.label_course.setAlignment(QtCore.Qt.AlignCenter)
        self.label_course.setObjectName("label_course")
        self.label = QtWidgets.QLabel(self.groupBox_1)
        self.label.setGeometry(QtCore.QRect(0, 34, 881, 501))
        self.label.setStyleSheet("QLabel {\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border-width: 15px;\n"
"border-radius:30px;\n"
"border-style: solid;\n"
"border-color: rgba(255, 255, 255, 255);\n"
"}\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox_1)
        self.label_2.setGeometry(QtCore.QRect(15, 478, 850, 41))
        self.label_2.setStyleSheet("QLabel{font: 75 18pt \"微软雅黑\";\n"
"background-color: rgba(93, 93, 93,0.5);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:10px;\n"
"\n"
"}")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(910, 100, 351, 531))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_background2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_background2.setGeometry(QtCore.QRect(0, 0, 351, 531))
        self.label_background2.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(255, 255, 255);")
        self.label_background2.setText("")
        self.label_background2.setScaledContents(False)
        self.label_background2.setObjectName("label_background2")
        self.label_checkNum = QtWidgets.QLabel(self.groupBox_2)
        self.label_checkNum.setGeometry(QtCore.QRect(10, 10, 141, 31))
        self.label_checkNum.setStyleSheet("border-radius:20px;\n"
"font: 75 16pt \"微软雅黑\";\n"
"color: rgb(0, 90, 255);")
        self.label_checkNum.setObjectName("label_checkNum")
        self.scrollArea = QtWidgets.QScrollArea(self.groupBox_2)
        self.scrollArea.setGeometry(QtCore.QRect(10, 40, 331, 481))
        self.scrollArea.setStyleSheet("QWidget{\n"
"background-color: rgba(255,255,255,0.7);\n"
"border-radius:10px;\n"
"}")
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 331, 481))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.label_uncheckNum = QtWidgets.QLabel(self.groupBox_2)
        self.label_uncheckNum.setGeometry(QtCore.QRect(235, 5, 81, 31))
        self.label_uncheckNum.setStyleSheet("border-radius:20px;\n"
"font: 75 10pt \"微软雅黑\";\n"
"color: rgb(0, 90, 255);")
        self.label_uncheckNum.setObjectName("label_uncheckNum")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox.setGeometry(QtCore.QRect(209, 10, 131, 22))
        self.comboBox.setStyleSheet("border-radius:20px;\n"
"font: 75 10pt \"微软雅黑\";\n"
"color: rgb(0, 90, 255);")
        self.comboBox.setEditable(False)
        self.comboBox.setMaxVisibleItems(50)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.label_background2.raise_()
        self.label_checkNum.raise_()
        self.scrollArea.raise_()
        self.comboBox.raise_()
        self.label_uncheckNum.raise_()
        self.label_info = QtWidgets.QLabel(self.centralwidget)
        self.label_info.setGeometry(QtCore.QRect(280, 30, 391, 51))
        self.label_info.setStyleSheet("\n"
"font: 75 20pt \"微软雅黑\";")
        self.label_info.setObjectName("label_info")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.dateTimeEdit.setGeometry(QtCore.QRect(960, 16, 231, 31))
        self.dateTimeEdit.setStyleSheet("border-radius:20px;\n"
"font: 16pt \"幼圆\" blod;\n"
"background-color: rgb(227, 229, 244);\n"
"")
        self.dateTimeEdit.setWrapping(False)
        self.dateTimeEdit.setFrame(False)
        self.dateTimeEdit.setReadOnly(True)
        self.dateTimeEdit.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.dateTimeEdit.setKeyboardTracking(False)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.BT_1 = QtWidgets.QPushButton(self.centralwidget)
        self.BT_1.setGeometry(QtCore.QRect(160, 640, 191, 61))
        self.BT_1.setStyleSheet("QPushButton {\n"
"image: url(\'resource/classinfor.png\');\n"
"background-color: rgba(255, 255, 255, 0.8);\n"
"border-radius: 20px;\n"
"font: 75 16pt \"微软雅黑\";\n"
"}\n"
"\n"
"QPushButton:hover{background:rgba(255,255,255,1.0);}")
        self.BT_1.setObjectName("BT_1")
        self.BT_2 = QtWidgets.QPushButton(self.centralwidget)
        self.BT_2.setGeometry(QtCore.QRect(390, 640, 191, 61))
        self.BT_2.setStyleSheet("QPushButton {\n"
"image: url(\'resource/check.png\');\n"
"background-color: rgba(255, 255, 255, 0.8);\n"
"border-radius: 20px;\n"
"font: 75 16pt \"微软雅黑\";\n"
"}\n"
"\n"
"QPushButton:hover{background:rgba(255,255,255,1.0);}")
        self.BT_2.setObjectName("BT_2")
        self.BT_3 = QtWidgets.QPushButton(self.centralwidget)
        self.BT_3.setGeometry(QtCore.QRect(610, 640, 191, 61))
        self.BT_3.setStyleSheet("QPushButton {\n"
"image: url(\'resource/notice.png\');\n"
"background-color: rgba(255, 255, 255, 0.8);\n"
"border-radius: 20px;\n"
"font: 75 16pt \"微软雅黑\";\n"
"}\n"
"\n"
"QPushButton:hover{background:rgba(255,255,255,1.0);}")
        self.BT_3.setObjectName("BT_3")
        self.BT_4 = QtWidgets.QPushButton(self.centralwidget)
        self.BT_4.setGeometry(QtCore.QRect(830, 640, 191, 61))
        self.BT_4.setStyleSheet("QPushButton {\n"
"image: url(\'resource/opendoor.png\');\n"
"background-color: rgba(255, 255, 255, 0.8);\n"
"border-radius: 20px;\n"
"font: 75 16pt \"微软雅黑\";\n"
"}\n"
"\n"
"QPushButton:hover{background:rgba(255,255,255,1.0);}")
        self.BT_4.setObjectName("BT_4")
        self.label_background.raise_()
        self.BT_exit.raise_()
        self.groupBox_1.raise_()
        self.label_info.raise_()
        self.dateTimeEdit.raise_()
        self.groupBox_2.raise_()
        self.BT_1.raise_()
        self.BT_2.raise_()
        self.BT_3.raise_()
        self.BT_4.raise_()
        self.label_logo.raise_()
        window_check.setCentralWidget(self.centralwidget)

        self.retranslateUi(window_check)
        self.comboBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(window_check)

    def retranslateUi(self, window_check):
        _translate = QtCore.QCoreApplication.translate
        window_check.setWindowTitle(_translate("window_check", "window_check"))
        self.BT_exit.setText(_translate("window_check", "退出"))
        self.label_2.setText(_translate("window_check", "请注视摄像头"))
        self.label_checkNum.setText(_translate("window_check", "已签到  0 人"))
        self.label_uncheckNum.setToolTip(_translate("window_check", "<html><head/><body><p><br/></p></body></html>"))
        self.label_uncheckNum.setText(_translate("window_check", "未签到人数"))
        self.comboBox.setToolTip(_translate("window_check", "<html><head/><body><p align=\"right\"><br/></p></body></html>"))
        self.comboBox.setItemText(0, _translate("window_check", "12"))
        self.label_info.setText(_translate("window_check", "教学区-图文信息中心TB504"))
        self.dateTimeEdit.setDisplayFormat(_translate("window_check", "yyyy-MM-dd HH:mm:ss"))
        self.BT_1.setToolTip(_translate("window_check", "<html><head/><body><p><br/></p></body></html>"))
        self.BT_1.setText(_translate("window_check", "          课程信息"))
        self.BT_2.setText(_translate("window_check", "      人像考勤"))
        self.BT_3.setText(_translate("window_check", "      通知公告"))
        self.BT_4.setText(_translate("window_check", "       一键开门"))
