# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window_classInfor.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_window_classInfor(object):
    def setupUi(self, window_classInfor):
        window_classInfor.setObjectName("window_classInfor")
        window_classInfor.resize(1294, 757)
        self.centralwidget = QtWidgets.QWidget(window_classInfor)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.label_background = QtWidgets.QLabel(self.centralwidget)
        self.label_background.setEnabled(True)
        self.label_background.setGeometry(QtCore.QRect(0, 0, 1280, 720))
        self.label_background.setStyleSheet("QLabel {\n"
"background-image: url(\'resource/background2.jpg\');\n"
"border-radius: 15px;\n"
"}")
        self.label_background.setText("")
        self.label_background.setScaledContents(False)
        self.label_background.setObjectName("label_background")
        self.label_logo = QtWidgets.QLabel(self.centralwidget)
        self.label_logo.setGeometry(QtCore.QRect(0, 10, 191, 41))
        self.label_logo.setStyleSheet("\n"
"border-radius:15px;")
        self.label_logo.setText("")
        self.label_logo.setPixmap(QtGui.QPixmap("resource/logo2.png"))
        self.label_logo.setScaledContents(True)
        self.label_logo.setObjectName("label_logo")
        self.BT_exit = QtWidgets.QPushButton(self.centralwidget)
        self.BT_exit.setGeometry(QtCore.QRect(1200, 10, 51, 41))
        self.BT_exit.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"font: 16pt \"楷体\" blod;\n"
"color: rgb(0, 90, 255);\n"
"}\n"
"\n"
"")
        self.BT_exit.setObjectName("BT_exit")
        self.groupBox_1 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_1.setGeometry(QtCore.QRect(10, 100, 881, 531))
        self.groupBox_1.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(255, 255, 255);")
        self.groupBox_1.setTitle("")
        self.groupBox_1.setObjectName("groupBox_1")
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox_1)
        self.tableWidget.setGeometry(QtCore.QRect(20, 51, 831, 461))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 blod")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tableWidget.setFont(font)
        self.tableWidget.setStyleSheet("QTableWidget::item::selected\n"
"{     \n"
"    background:rgba(0,170,255,0.4);\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    \n"
"    background-color: rgba(255, 138, 165,0.4);\n"
"    border-radius: 10px;\n"
"    border: 2px solid rgba(0,0,0,0.3);\n"
"}\n"
"\n"
"QTableWidget{font: 10pt \"微软雅黑\" blod;}\n"
" ")
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.NoPen)
        self.tableWidget.setRowCount(6)
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(50)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(50)
        self.label = QtWidgets.QLabel(self.groupBox_1)
        self.label.setGeometry(QtCore.QRect(240, 0, 371, 51))
        self.label.setStyleSheet("font: 20pt \"华文中宋\" blod;")
        self.label.setObjectName("label")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(910, 100, 351, 531))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_background2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_background2.setGeometry(QtCore.QRect(0, 0, 351, 531))
        self.label_background2.setStyleSheet("QLabel {\n"
"border-radius:20px;\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.label_background2.setText("")
        self.label_background2.setScaledContents(False)
        self.label_background2.setObjectName("label_background2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(110, 20, 151, 41))
        self.label_2.setStyleSheet("border-radius:20px;\n"
"font: 75 16pt \"微软雅黑\";\n"
"color: rgb(0, 90, 255);")
        self.label_2.setObjectName("label_2")
        self.label_course = QtWidgets.QLabel(self.groupBox_2)
        self.label_course.setGeometry(QtCore.QRect(20, 60, 321, 41))
        self.label_course.setStyleSheet("\n"
"font: 75 16pt \"微软雅黑\";")
        self.label_course.setText("")
        self.label_course.setAlignment(QtCore.Qt.AlignCenter)
        self.label_course.setObjectName("label_course")
        self.label_image = QtWidgets.QLabel(self.groupBox_2)
        self.label_image.setGeometry(QtCore.QRect(100, 120, 180, 180))
        self.label_image.setStyleSheet("")
        self.label_image.setText("")
        self.label_image.setScaledContents(True)
        self.label_image.setObjectName("label_image")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(30, 360, 71, 31))
        self.label_4.setStyleSheet("font: 75 10pt \"微软雅黑\";\n"
"\n"
"color: rgb(132, 132, 132);")
        self.label_4.setObjectName("label_4")
        self.label_teacher = QtWidgets.QLabel(self.groupBox_2)
        self.label_teacher.setGeometry(QtCore.QRect(110, 360, 221, 31))
        self.label_teacher.setStyleSheet("font: 75 11pt \"微软雅黑\";\n"
"")
        self.label_teacher.setText("")
        self.label_teacher.setObjectName("label_teacher")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(30, 410, 71, 31))
        self.label_5.setStyleSheet("font: 75 10pt \"微软雅黑\";\n"
"\n"
"color: rgb(132, 132, 132);")
        self.label_5.setObjectName("label_5")
        self.label_Class = QtWidgets.QLabel(self.groupBox_2)
        self.label_Class.setGeometry(QtCore.QRect(110, 410, 221, 31))
        self.label_Class.setStyleSheet("font: 75 10pt \"微软雅黑\";\n"
"")
        self.label_Class.setText("")
        self.label_Class.setObjectName("label_Class")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(30, 460, 71, 31))
        self.label_6.setStyleSheet("font: 75 10pt \"微软雅黑\";\n"
"\n"
"color: rgb(132, 132, 132);")
        self.label_6.setObjectName("label_6")
        self.label_ClassTime = QtWidgets.QLabel(self.groupBox_2)
        self.label_ClassTime.setGeometry(QtCore.QRect(110, 460, 221, 31))
        self.label_ClassTime.setStyleSheet("font: 75 11pt \"微软雅黑\";\n"
"")
        self.label_ClassTime.setText("")
        self.label_ClassTime.setObjectName("label_ClassTime")
        self.label_info = QtWidgets.QLabel(self.centralwidget)
        self.label_info.setGeometry(QtCore.QRect(410, 40, 481, 51))
        self.label_info.setStyleSheet("\n"
"font: 75 24pt \"微软雅黑\";")
        self.label_info.setObjectName("label_info")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.dateTimeEdit.setGeometry(QtCore.QRect(960, 16, 231, 31))
        self.dateTimeEdit.setStyleSheet("border-radius:20px;\n"
"font: 16pt \"幼圆\" blod;\n"
"background-color: rgb(227, 229, 244);\n"
"")
        self.dateTimeEdit.setWrapping(False)
        self.dateTimeEdit.setFrame(False)
        self.dateTimeEdit.setReadOnly(True)
        self.dateTimeEdit.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.dateTimeEdit.setKeyboardTracking(False)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.BT_1 = QtWidgets.QPushButton(self.centralwidget)
        self.BT_1.setGeometry(QtCore.QRect(160, 640, 191, 61))
        self.BT_1.setStyleSheet("QPushButton {\n"
"image: url(\'resource/classinfor.png\');\n"
"background-color: rgba(255, 255, 255, 0.8);\n"
"border-radius: 20px;\n"
"font: 75 16pt \"微软雅黑\";\n"
"}\n"
"\n"
"QPushButton:hover{background:rgba(255,255,255,1.0);}")
        self.BT_1.setObjectName("BT_1")
        self.BT_2 = QtWidgets.QPushButton(self.centralwidget)
        self.BT_2.setGeometry(QtCore.QRect(390, 640, 191, 61))
        self.BT_2.setStyleSheet("QPushButton {\n"
"image: url(\'resource/check.png\');\n"
"background-color: rgba(255, 255, 255, 0.8);\n"
"border-radius: 20px;\n"
"font: 75 16pt \"微软雅黑\";\n"
"}\n"
"\n"
"QPushButton:hover{background:rgba(255,255,255,1.0);}")
        self.BT_2.setObjectName("BT_2")
        self.BT_3 = QtWidgets.QPushButton(self.centralwidget)
        self.BT_3.setGeometry(QtCore.QRect(610, 640, 191, 61))
        self.BT_3.setStyleSheet("QPushButton {\n"
"image: url(\'resource/notice.png\');\n"
"background-color: rgba(255, 255, 255, 0.8);\n"
"border-radius: 20px;\n"
"font: 75 16pt \"微软雅黑\";\n"
"}\n"
"\n"
"QPushButton:hover{background:rgba(255,255,255,1.0);}")
        self.BT_3.setObjectName("BT_3")
        self.BT_4 = QtWidgets.QPushButton(self.centralwidget)
        self.BT_4.setGeometry(QtCore.QRect(830, 640, 191, 61))
        self.BT_4.setStyleSheet("QPushButton {\n"
"image: url(\'resource/opendoor.png\');\n"
"background-color: rgba(255, 255, 255, 0.8);\n"
"border-radius: 20px;\n"
"font: 75 16pt \"微软雅黑\";\n"
"}\n"
"\n"
"QPushButton:hover{background:rgba(255,255,255,1.0);}")
        self.BT_4.setObjectName("BT_4")
        self.label_background.raise_()
        self.label_logo.raise_()
        self.BT_exit.raise_()
        self.groupBox_1.raise_()
        self.label_info.raise_()
        self.dateTimeEdit.raise_()
        self.groupBox_2.raise_()
        self.BT_1.raise_()
        self.BT_2.raise_()
        self.BT_3.raise_()
        self.BT_4.raise_()
        window_classInfor.setCentralWidget(self.centralwidget)

        self.retranslateUi(window_classInfor)
        QtCore.QMetaObject.connectSlotsByName(window_classInfor)

    def retranslateUi(self, window_classInfor):
        _translate = QtCore.QCoreApplication.translate
        window_classInfor.setWindowTitle(_translate("window_classInfor", "window_classInfor"))
        self.BT_exit.setText(_translate("window_classInfor", "退出"))
        self.tableWidget.setToolTip(_translate("window_classInfor", "<html><head/><body><p><br/></p></body></html>"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("window_classInfor", "New Row"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("window_classInfor", "New Row"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("window_classInfor", "New Row"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("window_classInfor", "New Row"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("window_classInfor", "New Row"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("window_classInfor", "New Row"))
        self.label.setText(_translate("window_classInfor", "2023-2024 第1学期 第12周"))
        self.label_2.setText(_translate("window_classInfor", "• 正 在 进 行 •"))
        self.label_4.setText(_translate("window_classInfor", "授课教师："))
        self.label_5.setText(_translate("window_classInfor", "上课班级："))
        self.label_6.setText(_translate("window_classInfor", "上课时间："))
        self.label_info.setText(_translate("window_classInfor", "教学区-图文信息中心TB504"))
        self.dateTimeEdit.setDisplayFormat(_translate("window_classInfor", "yyyy-MM-dd HH:mm:ss"))
        self.BT_1.setToolTip(_translate("window_classInfor", "<html><head/><body><p><br/></p></body></html>"))
        self.BT_1.setText(_translate("window_classInfor", "          课程信息"))
        self.BT_2.setText(_translate("window_classInfor", "      人像考勤"))
        self.BT_3.setText(_translate("window_classInfor", "      通知公告"))
        self.BT_4.setText(_translate("window_classInfor", "       一键开门"))
